apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Echo Step A
        uses: cloudbees-io/echo@v1
        with:
          message: "This is step A calling the echo action."
      - name: Echo Step B
        uses: cloudbees-io/echo@v1
        with:
          message: "This is step B calling the echo action."
